defaults:
  - model: mlp3
  - env: mujoco_env
  - policy_loss: ppo
  - _self_

value_loss:
  _target_: src.loss.MSEValueLoss

seed: 42
output_dir: saved
device: "cpu"
project_name: "rl_experiments"
run_name: "test_longer"
trainer:
  num_epochs: 10
  num_minibatches: 4
  rollout_steps: 256
  total_timesteps: 10000000
  gamma: 0.99
  gae_lambda: 0.95
  normalize_advantages: true
  value_coef: 0.5
  entropy_coef: 0.0
  max_grad_norm: 0.5

num_updates: ${eval:'${trainer.total_timesteps} // int(${env.num_envs} * ${trainer.rollout_steps})'}

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.LinearLR
  start_factor: 1.0
  end_factor: ${eval:'1.0 / ${num_updates}'}
  total_iters: ${eval:'${num_updates} - 1'}